name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '19', '20', '21' ]
    steps:
      - name: Setup build
        uses: MOEAFramework/.github/actions/setup-build@main
        with:
          java-version: ${{ matrix.java }}
      - name: Run tests
        run: mvn test
