name: Validate and stage release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to publish
        required: true
      publish-github:
        description: 'Create draft GitHub release'
        default: true
        type: boolean
      publish-maven:
        description: 'Create Maven release'
        default: true
        type: boolean
      trigger-tests:
        description: 'Trigger integration tests'
        default: true
        type: boolean
      skip-validation:
        description: 'Skip version validations'
        default: false
        type: boolean

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup release
        uses: MOEAFramework/.github/actions/setup-build@main
        with:
          java-version: 19
          setup-git: true
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
          github-token: ${{ secrets.PAT }}
          gpg-signing-key: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Get project info
        uses: MOEAFramework/.github/actions/get-project-info@main
        with:
          expected-version: ${{ inputs.version }}
          skip-validation: ${{ inputs.skip-validation }}
      - name: Build and stage Maven artifacts
        if: ${{ inputs.publish-maven }}
        uses: MOEAFramework/.github/actions/publish-maven@main
        with:
          ossrh-username: ${{ secrets.OSSRH_USERNAME }}
          ossrh-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Stage GitHub release
        if: ${{ inputs.publish-github }}
        uses: MOEAFramework/.github/actions/publish-github@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger integration tests
        if: ${{ inputs.trigger-tests }}
        uses: MOEAFramework/.github/actions/integration-test@main
        with:
          github-token: ${{ secrets.PAT }}
