name: Validate and stage release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to publish
        required: true
      publish_github:
        description: 'Create draft GitHub release'
        default: true
        type: boolean
      publish_maven:
        description: 'Create Maven bundle'
        default: true
        type: boolean
      skip_validation:
        description: 'Skip version validations'
        default: false
        type: boolean

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: temurin
      - name: Validate version number
        if: ${{ ! inputs.skip_validation }}
        run: |
          [ "${{ inputs.version }}" == "$(cat pom.xml | grep -m 1 '<version>' | tr -d '<>/[:alpha:][:space:]')" ] || (>&2 echo "Version does not match value in pom.xml"; exit -1)
          [ "${{ inputs.version }}" == "$(cat README.md | grep -m 1 '<version>' | tr -d '<>/[:alpha:][:space:]')" ] || (>&2 echo "Version does not match value in README.md"; exit -1)
      - name: Build artifact
        run: mvn package javadoc:jar
      - name: Sign Maven artifacts and create bundle
        if: ${{ inputs.publish_maven }}
        run: |
          echo -n "${GPG_SIGNING_KEY}" | base64 --decode | gpg --import
          mkdir maven
          cp pom.xml maven/jmetal-plugin-${{ inputs.version }}.pom
          cp target/jmetal-plugin-${{ inputs.version }}.jar maven/jmetal-plugin-${{ inputs.version }}.jar
          cp target/jmetal-plugin-${{ inputs.version }}-jar-with-dependencies.jar maven/jmetal-plugin-${{ inputs.version }}-jar-with-dependencies.jar
          cp target/jmetal-plugin-${{ inputs.version }}-sources.jar maven/jmetal-plugin-${{ inputs.version }}-sources.jar
          cp target/jmetal-plugin-${{ inputs.version }}-javadoc.jar maven/jmetal-plugin-${{ inputs.version }}-javadoc.jar
          
          pushd maven
          gpg -ab jmetal-plugin-${{ inputs.version }}.pom
          gpg -ab jmetal-plugin-${{ inputs.version }}.jar
          gpg -ab jmetal-plugin-${{ inputs.version }}-jar-with-dependencies.jar
          gpg -ab jmetal-plugin-${{ inputs.version }}-sources.jar
          gpg -ab jmetal-plugin-${{ inputs.version }}-javadoc.jar
          
          jar -cvf jmetal-plugin-${{ inputs.version }}-bundle.jar *
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Upload Maven bundle
        if: ${{ inputs.publish_maven }}
        uses: actions/upload-artifact@v3
        with:
          name: Maven bundle
          path: maven/*-bundle.jar
      - name: Stage GitHub release
        if: ${{ inputs.publish_github }}
        run: |
          gh release create "v${{ inputs.version }}" --draft --title "Version ${{ inputs.version }}" \
            target/jmetal-plugin-${{ inputs.version }}.jar target/jmetal-plugin-${{ inputs.version }}-jar-with-dependencies.jar 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Release artifacts
          path: |
            target/jmetal-plugin-${{ inputs.version }}.jar
            target/jmetal-plugin-${{ inputs.version }}-jar-with-dependencies.jar
